select * from public.customer;
--Q1. What is the total revenue generated by male vs. female customers?
select c.Gender,
sum(c.purchase_amount) as Revenue 
from public.customer c
group by c.gender;

--Q2. Which customers used a discount but still spent more than the average purchase amount?
select 
c.customer_id,
c.purchase_amount 
from public.customer c
where c.discount_applied like 'Yes' and c.purchase_amount > (select avg(c.purchase_amount) from public.customer c)
;


SELECT 
c.customer_id,
c.purchase_amount
FROM public.customer c
CROSS JOIN (
  SELECT AVG(purchase_amount) AS avg_purchase_amount
  FROM public.customer
) a
WHERE c.discount_applied = 'Yes'
  AND c.purchase_amount > a.avg_purchase_amount;

--Q3. Which are the top 5 products with the highest average review rating?
select 
c.item_purchased,
round(avg(c.review_rating)::numeric,2) as Average_ratings
from public.customer c 
group by c.item_purchased
order by  Average_ratings desc
limit(5)
;

--Q4. Compare the average Purchase Amounts between Standard and Express Shipping.
select 
c.shipping_type,
round(avg(c.purchase_amount)::numeric,2)
from public.customer c
where c.shipping_type  in ('Express' , 'Standard')
group by c.shipping_type;

--Q5. Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.
select 
c.subscription_status,
round(avg(c.purchase_amount)::numeric,2) as avg_spend,
sum(c.purchase_amount) as total_revenue
from public.customer c
group by c.subscription_status;

--Q6. Which 5 products have the highest percentage of purchases with discounts applied?
--wrong
select 
c.item_purchased,
round(count(c.item_purchased)*100.0/count(*) over(),2) as percentage_share
from public.customer c
WHERE c.discount_applied = 'Yes'
group by c.item_purchased 
order by percentage_share
limit 5;

SELECT
    c.item_purchased,
    ROUND(
        100.0 * SUM(CASE WHEN c.discount_applied = 'Yes' THEN 1 ELSE 0 END)
        / COUNT(*),
        2
    ) AS percentage_share
FROM public.customer c
GROUP BY c.item_purchased
ORDER BY percentage_share DESC
LIMIT 5;

--Q7. Segment customers into New, Returning,and Loyal based on their total number of previous purchases, and show the count of each segment.
with customer_type as(
select c.customer_id,
c.previous_purchases,
case 
	when c.previous_purchases = 1 then 'new'
	when c.previous_purchases between 2 and 10 then 'returning'
	else 'loyal'
end as customer_segment
from customer c 
)
select customer_segment, count(*) as "Number of Customers"
from customer_type
group by customer_segment;

--Q8. What are the top 3 most purchased products within each category?
with cte as(
select 
c.category,
c.item_purchased,
count(*) as purchase_count,
rank() over(
partition by c.category 
order by count(*) desc
) as product_rank
from public.customer c 
group by c.category,c.item_purchased
)
select 
category,
item_purchased,
purchase_count
from cte
where product_rank >= 3
order by category, purchase_count DESC;

--Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
select 
c.subscription_status,
count(c.customer_id ) as repeat_buyers
from public.customer c
where c.previous_purchases >= 5 
group by c.subscription_status ;


--Q10. What is the revenue contribution of each age group?
select
c.age_group,
sum(c.purchase_amount) as total_revenue
from customer c 
group by age_group 
order by total_revenue desc;





